server:
  port: 8001


mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: com.springcloud.demo.entities       # 所有Entity别名类所在包
  mapper-locations: classpath:mybatis/mapper/**/*.xml       # mapper映射文件


spring:
  application:
    name: dept-demo-provider                                #对外暴露的微服务名称
  cloud:
    config: false
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver             # mysql驱动包
    # 数据库名称,mysql8以上必须要加这些后缀
    url: jdbc:mysql://localhost:3306/cloudDB01?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: 123456
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                                  # 等待连接获取的最大超时时间




eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      #defaultZone: http://localhost:7001/eureka/
      defaultZone: http://eureka-7001:7001/eureka/,http://eureka-7002:7002/eureka/,http://eureka-7003:7003/eureka/
  instance:
    instance-id: dept-demo-provider-hystrix-8001
    prefer-ip-address: true     #访问路径可以显示IP地址

#配置actuator/info信息，需要在pom中引入spring-boot-starter-actuator
info:
  app.name: springcloud-demo
  company.name: www.xjx.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$

feign:
  hystrix:
    enabled: true