server:
  port: 9557

spring:
  application:
    name: dept-demo-gateWay
  cloud:
    gateway:
      routes:
        - id: gateway-test
          uri: lb://dept-demo-provider/dept/**   #目标地址
          predicates:
            - Path=/dept/**   #映射地址






eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://localhost:7001/eureka/
  instance:
    instance-id: dept-demo-gateWay-9557
    prefer-ip-address: true

#配置actuator/info信息，需要在pom中引入spring-boot-starter-actuator
info:
  app.name: springcloud-demo
  company.name: www.xjx.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$














































