server:
  port: 7002

eureka:
  instance:
    hostname: eureka-7002 #eureka服务端的实例名称
  client:
    register-with-eureka: false #false表示不向注册中心注册自己。
    fetch-registry: false #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url:    #http://eureka-7001:7001/eureka/地址中必须要添加eureka/否则客户端无法注册到集群中，但是直接访问这个地址会报404错误
      defaultZone: http://eureka-7001:7001/eureka/,http://eureka-7003:7003/eureka/
      #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址。
      #http://localhost:7001/
