server:
  port: 3344
spring:
  application:
    name: dept-demo-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/xiao-moon/springcloud-config.git #Github上面git仓库名字

eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      #defaultZone: http://localhost:7001/eureka/
      defaultZone: http://eureka-7001:7001/eureka/,http://eureka-7002:7002/eureka/,http://eureka-7003:7003/eureka/
  instance:
    instance-id: dept-demo-config-server-3344
    prefer-ip-address: true     #访问路径可以显示IP地址
